# Generated by Django 3.2 on 2021-04-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numRevievs',
            new_name='numReviews',
        ),
    ]
